# Generated by Django 5.2.8 on 2025-11-21 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='main_category',
            new_name='main_cat',
        ),
        migrations.RenameField(
            model_name='sub_category',
            old_name='main_category',
            new_name='main_cat',
        ),
    ]
