# Generated by Django 5.2.8 on 2025-11-21 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_main_category_product_main_cat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productdetails', to='myapp.sub_category'),
        ),
    ]
