# Generated by Django 5.2.8 on 2025-11-22 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product_sub_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mini_sub_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mini_sbcat_name', models.CharField(max_length=100)),
                ('main_cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mini_subcategories', to='myapp.main_category')),
                ('sub_cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mini_subcategories', to='myapp.sub_category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='mini_sub_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productdetails', to='myapp.mini_sub_category'),
        ),
    ]
