# Generated by Django 5.2.8 on 2025-11-23 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_mini_sub_category_product_mini_sub_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='mini_sub_cat',
        ),
        migrations.CreateModel(
            name='Sub_sub_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sb_sbcat_name', models.CharField(max_length=100)),
                ('main_cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_subcategories', to='myapp.main_category')),
                ('sub_cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_subcategories', to='myapp.sub_category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sub_sub_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productdetails', to='myapp.sub_sub_category'),
        ),
        migrations.DeleteModel(
            name='Mini_sub_category',
        ),
    ]
