# Generated by Django 5.2.8 on 2025-11-24 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_product_mini_sub_cat_sub_sub_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sub_sub_cat',
        ),
        migrations.DeleteModel(
            name='Sub_sub_category',
        ),
    ]
