# Generated by Django 5.2.8 on 2025-11-24 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_product_sub_sub_cat_delete_sub_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='main_cat',
        ),
    ]
