# Generated by Django 5.2.8 on 2025-11-24 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_product_product_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productdetails', to='myapp.main_category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.sub_category'),
        ),
    ]
