# Generated by Django 5.2.8 on 2025-11-24 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_product_main_cat_alter_product_sub_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.main_category'),
        ),
    ]
